Abdul Naeem B
24-27-15
M.Tech Data Science
Assignment 2

In [1]:
import numpy as np
import pandas as pd

Q1
a) Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange
b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function
c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.
d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)
e) Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.
f) Write code to do the following:
(i) Slice out the second row of var2 and print it.
(ii) Slice out the last column of var2 using the -1 notation and print it.
(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [53]:
var1 = np.arange(0,30)

In [54]:
var1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
var1.shape

(30,)

In [56]:
var2 = np.reshape(var1,(5,6))

In [57]:
var2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
var2.shape

(5, 6)

In [59]:
var3 = np.reshape(var2,(5,3,2))

In [60]:
var3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [61]:
var3.shape

(5, 3, 2)

In [63]:
var2[1][0] = -1

In [64]:
var2

array([[ 0,  1,  2,  3,  4,  5],
       [-1,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [67]:
var1

array([ 0,  1,  2,  3,  4,  5, -1,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [68]:
var3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[-1,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

Reshape does return a view so the value changes to the original

In [75]:
np.sum(var3,axis=1)

array([[ 6,  9],
       [17, 27],
       [42, 45],
       [60, 63],
       [78, 81]])

In [77]:
np.sum(var3,axis=2)

array([[ 1,  5,  9],
       [ 6, 17, 21],
       [25, 29, 33],
       [37, 41, 45],
       [49, 53, 57]])

In [78]:
np.sum(var3,axis=(0,2))

array([118, 145, 165])

In [82]:
var2[1]

array([-1,  7,  8,  9, 10, 11])

In [84]:
var2[:,-1]

array([ 5, 11, 17, 23, 29])

In [89]:
var2[:2,-2:]

array([[ 4,  5],
       [10, 11]])

Q2
a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.
b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.
c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )
d) You don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend
data set of 50 independent and identically-distributed vectors from a log-normal
distribution.
e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.
f) Now standardize the data matrix by 1) subtracting the mean off of each column,
and 2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.

In [17]:
new_var1 = np.arange(10)

In [18]:
new_var1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
new_var1 = new_var1+1

In [24]:
new_var1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
matrix = new_var1 + np.reshape(new_var1,(10,1))

In [26]:
matrix

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [55]:
data = np.exp(np.random.randn(50,5))

In [56]:
data

array([[ 0.26997292,  0.11579961,  0.86849538,  3.21533479, 10.7408329 ],
       [ 0.16676773,  1.21346898,  0.41911035,  3.16040047,  0.97741163],
       [ 2.97058237,  3.61463836,  0.88204056,  0.73663802,  2.70343879],
       [ 8.07307765,  0.20229469,  0.43769401,  0.33447606,  2.21623335],
       [ 4.06125156,  2.29147231,  0.96692146,  0.96119696,  0.08224161],
       [ 4.6236921 ,  0.22268981,  1.01680155,  0.77687994,  0.75132984],
       [ 1.34594178,  1.03751885,  0.50581821,  1.48701679,  0.63130166],
       [ 1.86656545,  3.80551413,  1.17202691,  0.45761372,  0.4531393 ],
       [ 0.93707209,  1.52649947,  2.1661852 ,  0.95047752,  0.98175865],
       [ 0.35688613,  0.46476873,  0.77715987,  0.9243357 ,  1.08999304],
       [ 0.92334376,  0.52662065,  0.63758081,  1.55999896,  0.33361562],
       [ 0.76090607,  0.35617596,  0.3620507 ,  0.25718388,  0.71901332],
       [ 1.51694001,  0.87039329,  0.55187223,  2.49367821,  0.57267356],
       [ 3.37066793,  0.34244941,  0.5

In [57]:
mean = np.mean(data,axis=0)
mean

array([1.83315729, 1.58034837, 1.27433598, 1.87137672, 1.40221385])

In [58]:
std = np.std(data,axis=0)
std

array([2.15555836, 2.13490241, 1.36501722, 2.59385198, 1.82142127])

In [59]:
norm_data = (data - mean) / std
norm_data

array([[-0.72518768, -0.68600267, -0.29731537,  0.51813214,  5.12710552],
       [-0.77306632, -0.17184832, -0.62653102,  0.49695348, -0.23322568],
       [ 0.52767074,  0.9528726 , -0.28739229, -0.43747242,  0.71440087],
       [ 2.89480465, -0.6454879 , -0.61291679, -0.59251672,  0.44691445],
       [ 1.03365064,  0.33309436, -0.22520926, -0.35089888, -0.72469355],
       [ 1.29457632, -0.63593472, -0.18866754, -0.42195807, -0.35734952],
       [-0.22602752, -0.25426432, -0.56300958, -0.14818113, -0.42324761],
       [ 0.01549861,  1.04227985, -0.07495075, -0.54504382, -0.52106263],
       [-0.41570909, -0.02522312,  0.65336114, -0.35503152, -0.23083907],
       [-0.68486717, -0.52254362, -0.36422699, -0.36510989, -0.17141603],
       [-0.42207789, -0.49357184, -0.46648142, -0.12004454, -0.58668373],
       [-0.49743548, -0.57340907, -0.66833244, -0.62231494, -0.37509199],
       [-0.14669855, -0.33254685, -0.5292708 ,  0.23991403, -0.45543571],
       [ 0.7132772 , -0.57983866, -0.5

In [63]:
norm_mean = np.mean(norm_data,axis=0)
norm_mean

array([-1.42108547e-16, -4.32986980e-17, -9.18709553e-17, -1.22124533e-17,
        3.33066907e-18])

In [61]:
norm_std = np.std(norm_data,axis=0)
norm_std

array([1., 1., 1., 1., 1.])

Q3
a) A Vandermonde matrix is a matrix generated from a vector in which each column
of the matrix is an integer power starting from zero. So, if I have a column vector
[x1, x2, . . . , xN]
T
, then the associated (square) Vandermonde matrix would be

Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T
for

any N. Do it without using a loop. Here’s a stub to get you started:
def vandermonde (N):
vec = np.arange (N) +1
Use your function for N = 12, store it in variable named vander, and print the
result.
b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.
c) First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.
d) Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?

In [23]:
def vandermonde(N):
    vec = np.arange(1,N+1)
    vander_matrix = vec[:, np.newaxis] ** np.arange(N)
    return vander_matrix

In [75]:
vander = vandermonde(12)
print(vander)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [77]:
x = np.ones(12)

In [78]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
b = np.dot(vander,x)

In [80]:
b

array([1.20000000e+01, 4.09500000e+03, 2.65720000e+05, 5.59240500e+06,
       6.10351560e+07, 4.35356467e+08, 2.30688120e+09, 1.22713351e+09,
       9.43953692e+08, 3.73692871e+09, 3.10225064e+08, 3.10073456e+09])

In [81]:
v_inv = np.linalg.inv(vander)
x_solved = np.dot(v_inv,b)

In [82]:
x_solved

array([1.00000572, 0.99735641, 1.00311279, 0.999506  , 1.00002861,
       0.99999857, 1.0000001 , 1.        , 1.        , 1.        ,
       1.        , 1.        ])

It is due to the inherent numerical presicion issues in the inverion of the matrix, especially with large matrices which causes slight deviation from the expected solution of an array of all 1's

In [83]:
x_solved2 = np.linalg.solve(vander,b)
x_solved2

array([1.00000067, 0.99999715, 1.00000411, 0.99999733, 1.00000089,
       0.99999984, 1.00000002, 1.        , 1.        , 1.        ,
       1.        , 1.        ])

In [84]:
closeness = np.subtract(x_solved,x_solved2)
closeness

array([ 5.05639097e-06, -2.64073753e-03,  3.10868088e-03, -4.91328773e-04,
        2.77174300e-05, -1.26618616e-06,  8.74412640e-08, -2.82150814e-09,
        8.21880342e-11, -1.77635684e-15,  6.66133815e-16,  2.22044605e-16])

Github Repository Link - https://github.com/AbdulNaeemB/Abdul_Naeem_B_24-27-15/blob/1a89f225f5a4559271f4545cbbeb383e9244f350/Assn2_Abdul_Naeem_B_24-27-15.ipynb